version: '3.8'
services:
  api:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo:6.0
    ports:
      - '27017:27017'
  redis:
    image: redis:7
    ports:
      - '6379:6379'
